### ISSUE TITLE
Hero section with linear gradient and parallax effect

### ISSUE THREAD

**Issue by rajutkarsh07** [SharjeelDev/wild-life-photography#5]
I will make hero section like this one and add parallax effect in it 
![image](https://user-images.githubusercontent.com/49344502/194621299-0ad8d2e9-f910-4394-8bac-107a4e983a95.png)

**Comment by rajutkarsh07** [comment]
please assign me this issue and add hacktoberfest tag in it

**Comment by ZainabR11** [comment]
Hello Team, I'm excited to lead the creation of  Hero Section!

**Comment by sharjeelyunus** [comment]
sure @ZainabR11 , assigning you this ticket

**Comment by ZainabR11** [comment]
Thankyou for assigning.

**Comment by ZainabR11** [comment]
I have pulled request. Kindly consider. Zainab Rizwan-------- Original message --------From: Sharjeel Yunus ***@***.***>Date: Fri, 29 Sep 2023, 1:06 amTo: sharjeelyunus/wild-life-photography ***@***.***>Cc: ZainabR11 ***@***.***>, Assign ***@***.***>Subject: Re: [sharjeelyunus/wild-life-photography] Hero section with linear gradient and parallax effect (Issue #5)
Assigned #5 to @ZainabR11.
